### ISSUE TITLE
优化数学公式

### ISSUE THREAD

**Issue by syx-413** [zhangwt-cn/anki-card#6]
### 原文输入
 [!definition]+ 2.1 (导数)
> 
> 
> 设函数 $f$ 在 $x_0$ 的附近有定义.若存在 $\alpha\in\mathbb{R}$ 使得
$$\begin{aligned}\lim_{\Delta x\to0}\frac{f(x_0+\Delta x)-f(x_0)}{\Delta x}=\lim_{\Delta x\to0}\frac{\Delta f(x)}{\Delta x}=a.\end{aligned}$$
则称 $f(x)$ 在 $x_0$ 处**可导** (derivable), $a$ 称为 $f$ 在 $x_0$ 处的**导数** (derivative), 记作 $f^{\prime}(x_0)=a.$ 主 注意到导数也是一个局部概念.
 在物理中，经常需要对时间的函数求导.设关于时间 $t$ 的函数 $\varphi(t)$,它的导数可以记作 $\dot{\varphi}$,这个记号称为 Newton记号.
令$x=x_0+\Delta x$,则导数的定义式变为
$$\begin{aligned}f'(x_0):=\lim_{x\to x_0}\frac{f(x)-f(x_0)}{x-x_0}.\end{aligned}$$
> 现在可以用导数来定义显式曲线切线的概念.

 > [!definition|2.2]  (显式曲线的切线) 
> 
设函数$f$ 在$x_0$处可导.则过点 $P(x_0,f(x_0))$ 斜率为 $f^{\prime}(x_0)$ 的直线$\begin{aligned}y=f(x_0)+f'(x_0)(x-x_0)\end{aligned}$称为曲线 $y=f(x)$ 在 $P$ 处的**切线** (tangent line). 过点 $P$ 且**垂直于切线**的直线称为曲线 $y=f(x)$ 在 $P$ 处的**法线** (normal line).

事实上，曲线在某一点的切线的**斜率**就是导数的**几何意义**. 从几何直观上看，在某点可导意味着在这一点“光滑”,“有棱角”的地方都是不可导的，也没有切线. 导数定义“线密度”的例子.

> 既然有**单侧极限**，自然可以定义**单侧导数.** 

> [!definition|2.3] (单侧导数)
> 定义 
 设函数 $f.$
 (1) 若 $f$在$x_0$ 的左邻域 $N_r^-(x_0)$ 有定义，且存在 $\alpha\in\mathbb{R}$,使得 $$
\lim_{\Delta x\to0-}\frac{f(x_0+\Delta x)-f(x_0)}{\Delta x}=a.$$
则称函数 $f$ 在 $x_0$ 的左侧可导，$a$ 称为 $f(x)$ 在 $x_0$ 处的**左导数** (left derivative), 记作 $f_{-}^{\prime}(x_0)$.
(2) 若 $f$在$x_0$ 的右邻域 $N^+(x_0)$ 有定义，且存在 $\alpha\in\mathbb{R}$,使得 $$
\lim_{\Delta x\to0+}\frac{f(x_0+\Delta x)-f(x_0)}{\Delta x}=a.$$
则称函数$f$ 在$x_0$的右侧可导，$a$ 称为 $f(x)$ 在 $x_0$ 处的**右导数** (right derivative), 记作 $f_+^{\prime}(x_0)$. 
 左导数和右导数统称**单侧导数** (one-sided derivative).

> [!proposition|2.1]
> 
设函数$f$在邻域$N_r( x_0)$有定义.则 $f(x)$ 在$x_0$ 处可导且 $f^{\prime}(x_0)=\alpha$ 当且仅当
$$
f_-^{\prime}(x_0)=f_+^{\prime}(x_0)=a.
$$

从几何直观上看, 曲线上不可导处 “**不光滑**”, 存在 “**毛刺**”.

上述命题的逆命题可以用来判断函数**不可导**.

> [!theorem|2.2] 可导和连续的关系
> 
设函数 $f$ 在 $x_0$ 处可导，则 $f(x)$ 在 $x_0$ 处连续.
证明 由于 $f$ 在 $x_{0}$ 处可导，于是有
$$\lim_{x\to x_0}\left[f(x)-f(x_0)\right]=\lim_{x\to x_0}\left[\frac{f(x)-f(x_0)}{x-x_0}\cdot(x-x_0)\right]=\lim_{x\to x_0}\frac{f(x)-f(x_0)}{x-x_0}\cdot\lim_{x\to x_0}(x-x_0)=0.$$
这表明$\lim_{x\to x_0}f(x)=f(x_0)$.于是可知$f(x)$ 在$x_0$处连续.

注 函数在某处连续是在该处可导的**必要条件**，但不是**充分条件**，因此“**可导**”比“**连续**”更强.

> [!theorem|2.3] 反函数的求导法则
> 
设函数 $y=f(x)$ 在区间 $I$ 上连续且严格单调.若 $f(x)$ 在 $x_0\in I$ 处可导，且 $f^{\prime}(x_0)\neq0$,则 $f(x)$ 的反函数 $x=f^{-1}(y)$ 在 $y_0=f(x_0)$ 处可导，且$$
\left(f^{-1}\right)^{\prime}(y_0)=\frac1{f^{\prime}(x_0)}.
$$

<mark style="background: #FFF3A3A6;">证明</mark> 由[[第一章 函数与极限#^84324b]]可知 $f^{-1}(y)$ 在 $y_0$ 上连续.因此当 $y\to y_0$ 时$x\to x_0.$ 由导数的定义可知
   $$\left(f^{-1}\right)^{\prime}(y_0)=\lim_{y\to y_0}\frac{f^{-1}(y)-f^{-1}(y_0)}{y-y_0}=\lim_{x\to x_0}\frac{x-x_0}{f(x)-f(x_0)}=\lim_{x\to x_0}\left[\frac{f(x)-f(x_0)}{x-x_0}\right]^{-1}=\frac{1}{f^{\prime}(x)}$$
<mark style="background: #FFF3A3A6;">注</mark> 设 $y=f\left(x\right)$,用 Leibniz 记号可以将以上定理改写为
 $$\frac{d x}{dy}=\frac{1}{\frac{dy}{dx}} $$
我们可以从几何角度来理解反函数的求导法则.如图2.1,设函数 $y=f(x)$ 在区间 $I$ 上连续且严格单调递增.
若$f(x)$ 在$x_0\in I$ 处可导，且 $f^{\prime}(x_0)\neq0$.令 $y_0=f(x_0)$,则 $y=f(x)$ 在 $(x_0,y_0)$ 处有切线 $l$,且 $l$ 的斜率不为零，即它与$x$ 轴不平行.设$l$ 与$x$ 轴和 y 轴的夹角分别为$\alpha$ 和 $\beta$.则 $\alpha+\beta=\pi/2.$ 因此
 $$\tan\alpha=\tan\left(\frac{\pi}{2}-\beta\right)=\cot\alpha=\frac{1}{\tan\beta}.$$
容易知道  $$\tan\alpha=f'(x_0),\quad\tan\beta=\begin{pmatrix}f^{-1}\end{pmatrix}'(y_0).$$
	于是就得到了反函数的求导法则.
---
## 输出 
什么是导数?	设函数 f 在 x_0 的附近有定义. 若存在 α∈ℝ 使得 lim(Δx→0) (f(x_0 + Δx) - f(x_0))/Δx = α，则称 f(x) 在 x_0 处可导，α 称为 f 在 x_0 处的导数，记作 f'(x_0) = α.

## 可以优化一下数学表达式的输出吗？

**Comment by zhangwt-cn** [comment]
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/0e6cc73d-a641-4d99-89dc-e9036db030f5">

已经支持了，你再试下看看
